In [1]:
import pandas as pd 
import numpy as np

In [2]:
df1 = pd.read_csv('D:\datasets\part_01.csv')
df2 = pd.read_csv('D:\datasets\part_02.csv')
df3 = pd.read_csv('D:\datasets\part_03.csv')
df4 = pd.read_csv('D:\datasets\part_04.csv')
df5 = pd.read_csv('D:\datasets\part_05.csv')
df6 = pd.read_csv('D:\datasets\part_06.csv')
df7 = pd.read_csv('D:\datasets\part_07.csv')
df8 = pd.read_csv('D:\datasets\part_08.csv')
df9 = pd.read_csv('D:\datasets\part_09.csv')
df10 = pd.read_csv('D:\datasets\part_10.csv')
df11 = pd.read_csv('D:\datasets\part_11.csv')
df12 = pd.read_csv('D:\datasets\part_12.csv')

In [3]:
df_all = pd.DataFrame()

In [38]:
df1.shape

(177595, 30)

In [39]:
df2.shape

(177595, 12)

In [40]:
df3.shape

(177595, 30)

In [41]:
df4.shape

(177595, 14)

In [42]:
df5.shape

(177595, 11)

In [43]:
df6.shape

(177595, 24)

In [44]:
df7.shape

(177595, 14)

In [45]:
df8.shape

(177595, 30)

In [46]:
df9.shape

(177595, 30)

In [47]:
df10.shape

(177595, 24)

In [48]:
df11.shape

(177595, 12)

In [49]:
df12.shape

(177595, 11)

In [5]:
a1 = pd.concat([df5, df12], ignore_index=True)
a2 = pd.concat([df6, df10], ignore_index=True)
a3 = pd.concat([df2, df11], ignore_index=True)
a4 = pd.concat([df1, df9], ignore_index=True)
a5 = pd.concat([df3, df8], ignore_index=True)
a6 = pd.concat([df4, df7], ignore_index=True)

In [6]:
df_all = a1.merge(a2, left_on='ID', right_on='ID')
df_all = df_all.merge(a3, left_on='ID', right_on='ID')
df_all = df_all.merge(a4, left_on='ID', right_on='ID')
df_all = df_all.merge(a5, left_on='ID', right_on='ID')
df_all = df_all.merge(a6, left_on='ID', right_on='ID')
df_all = df_all.sort_values(by='ID')
df_all

,ID,CNT_ACCEPTS_MTP,CNT_ACCEPTS_TK,PRC_ACCEPTS_A_AMOBILE,PRC_ACCEPTS_A_ATM,PRC_ACCEPTS_A_EMAIL_LINK,PRC_ACCEPTS_A_MTP,PRC_ACCEPTS_A_POS,PRC_ACCEPTS_A_TK,PRC_ACCEPTS_MTP,...,CLNT_SETUP_TENOR,CLNT_TRUST_RELATION,CR_PROD_CNT_CC,CR_PROD_CNT_CCFP,CR_PROD_CNT_IL,CR_PROD_CNT_PIL,CR_PROD_CNT_TOVR,CR_PROD_CNT_VCU,PACK,TARGET
179094,146841,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.593023,NaN,0,0,0,0,0,0,K01,0
5351,146842,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.587647,NaN,0,0,0,0,0,0,102,0
206996,146843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.587647,NaN,0,0,0,0,0,0,102,0
145569,146844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.583333,NaN,0,0,0,0,0,0,K01,0
329776,146845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.583333,NaN,0,0,0,0,0,0,102,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352062,590822,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.963872,NaN,0,0,0,0,2,0,104,0
255813,590823,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.963872,NaN,0,0,0,0,0,0,104,0
233095,590825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.966560,NaN,0,0,0,0,0,0,K01,0
353508,590826,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.966560,NaN,0,0,0,0,1,0,O01,0
330689,590828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.961184,SISTER,0,0,0,0,1,0,K01,1

In [7]:
df_all = df_all.sort_values(by='ID')
df_all

,ID,CNT_ACCEPTS_MTP,CNT_ACCEPTS_TK,PRC_ACCEPTS_A_AMOBILE,PRC_ACCEPTS_A_ATM,PRC_ACCEPTS_A_EMAIL_LINK,PRC_ACCEPTS_A_MTP,PRC_ACCEPTS_A_POS,PRC_ACCEPTS_A_TK,PRC_ACCEPTS_MTP,...,CLNT_SETUP_TENOR,CLNT_TRUST_RELATION,CR_PROD_CNT_CC,CR_PROD_CNT_CCFP,CR_PROD_CNT_IL,CR_PROD_CNT_PIL,CR_PROD_CNT_TOVR,CR_PROD_CNT_VCU,PACK,TARGET
179094,146841,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.593023,NaN,0,0,0,0,0,0,K01,0
5351,146842,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.587647,NaN,0,0,0,0,0,0,102,0
206996,146843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.587647,NaN,0,0,0,0,0,0,102,0
145569,146844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.583333,NaN,0,0,0,0,0,0,K01,0
329776,146845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.583333,NaN,0,0,0,0,0,0,102,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352062,590822,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.963872,NaN,0,0,0,0,2,0,104,0
255813,590823,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.963872,NaN,0,0,0,0,0,0,104,0
233095,590825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.966560,NaN,0,0,0,0,0,0,K01,0
353508,590826,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.966560,NaN,0,0,0,0,1,0,O01,0
330689,590828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.961184,SISTER,0,0,0,0,1,0,K01,1

In [8]:
df_all.columns

Index(['ID', 'CNT_ACCEPTS_MTP', 'CNT_ACCEPTS_TK', 'PRC_ACCEPTS_A_AMOBILE',
       'PRC_ACCEPTS_A_ATM', 'PRC_ACCEPTS_A_EMAIL_LINK', 'PRC_ACCEPTS_A_MTP',
       'PRC_ACCEPTS_A_POS', 'PRC_ACCEPTS_A_TK', 'PRC_ACCEPTS_MTP',
       ...
       'CLNT_SETUP_TENOR', 'CLNT_TRUST_RELATION', 'CR_PROD_CNT_CC',
       'CR_PROD_CNT_CCFP', 'CR_PROD_CNT_IL', 'CR_PROD_CNT_PIL',
       'CR_PROD_CNT_TOVR', 'CR_PROD_CNT_VCU', 'PACK', 'TARGET'],
      dtype='object', length=116)

In [9]:
df_all.drop_duplicates(keep = False)

,ID,CNT_ACCEPTS_MTP,CNT_ACCEPTS_TK,PRC_ACCEPTS_A_AMOBILE,PRC_ACCEPTS_A_ATM,PRC_ACCEPTS_A_EMAIL_LINK,PRC_ACCEPTS_A_MTP,PRC_ACCEPTS_A_POS,PRC_ACCEPTS_A_TK,PRC_ACCEPTS_MTP,...,CLNT_SETUP_TENOR,CLNT_TRUST_RELATION,CR_PROD_CNT_CC,CR_PROD_CNT_CCFP,CR_PROD_CNT_IL,CR_PROD_CNT_PIL,CR_PROD_CNT_TOVR,CR_PROD_CNT_VCU,PACK,TARGET
179094,146841,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.593023,NaN,0,0,0,0,0,0,K01,0
5351,146842,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.587647,NaN,0,0,0,0,0,0,102,0
206996,146843,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.587647,NaN,0,0,0,0,0,0,102,0
145569,146844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.583333,NaN,0,0,0,0,0,0,K01,0
329776,146845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.583333,NaN,0,0,0,0,0,0,102,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
352062,590822,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.963872,NaN,0,0,0,0,2,0,104,0
255813,590823,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,8.963872,NaN,0,0,0,0,0,0,104,0
233095,590825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.966560,NaN,0,0,0,0,0,0,K01,0
353508,590826,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.966560,NaN,0,0,0,0,1,0,O01,0
330689,590828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.961184,SISTER,0,0,0,0,1,0,K01,1

In [10]:
df_all.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 355190 entries, 179094 to 330689
Data columns (total 116 columns):
 #    Column                       Dtype
---   ------                       -----
 0    ID                           int64
 1    CNT_ACCEPTS_MTP              float64
 2    CNT_ACCEPTS_TK               float64
 3    PRC_ACCEPTS_A_AMOBILE        float64
 4    PRC_ACCEPTS_A_ATM            float64
 5    PRC_ACCEPTS_A_EMAIL_LINK     float64
 6    PRC_ACCEPTS_A_MTP            float64
 7    PRC_ACCEPTS_A_POS            float64
 8    PRC_ACCEPTS_A_TK             float64
 9    PRC_ACCEPTS_MTP              float64
 10   PRC_ACCEPTS_TK               float64
 11   REST_AVG_CUR                 float64
 12   REST_AVG_PAYM                float64
 13   REST_DYNAMIC_CC_1M           float64
 14   REST_DYNAMIC_CC_3M           float64
 15   REST_DYNAMIC_CUR_1M          float64
 16   REST_DYNAMIC_CUR_3M          float64
 17   REST_DYNAMIC_FDEP_1M         float64
 18   REST_DYNAMIC_FDEP_3M         float64
 19   REST_DYNAMIC_IL_1M           float64
 20   REST_DYNAMIC_IL_3M           float64
 21   REST_DYNAMIC_PAYM_1M         float64
 22   REST_DYNAMIC_PAYM_3M         float64
 23   REST_DYNAMIC_SAVE_3M         float64
 24   TURNOVER_CC                  float64
 25   TURNOVER_DYNAMIC_CC_1M       float64
 26   TURNOVER_DYNAMIC_CC_3M       float64
 27   TURNOVER_DYNAMIC_CUR_1M      float64
 28   TURNOVER_DYNAMIC_CUR_3M      float64
 29   TURNOVER_DYNAMIC_IL_1M       float64
 30   TURNOVER_DYNAMIC_IL_3M       float64
 31   TURNOVER_DYNAMIC_PAYM_1M     float64
 32   TURNOVER_DYNAMIC_PAYM_3M     float64
 33   TURNOVER_PAYM                float64
 34   AGE                          int64
 35   APP_CAR                      object
 36   APP_COMP_TYPE                object
 37   APP_DRIVING_LICENSE          object
 38   APP_EDUCATION                object
 39   APP_EMP_TYPE                 object
 40   APP_KIND_OF_PROP_HABITATION  object
 41   APP_MARITAL_STATUS           object
 42   APP_POSITION_TYPE            object
 43   APP_REGISTR_RGN_CODE         float64
 44   APP_TRAVEL_PASS              object
 45   AMOUNT_RUB_ATM_PRC           float64
 46   AMOUNT_RUB_CLO_PRC           float64
 47   AMOUNT_RUB_NAS_PRC           float64
 48   AMOUNT_RUB_SUP_PRC           float64
 49   CNT_TRAN_ATM_TENDENCY1M      float64
 50   CNT_TRAN_ATM_TENDENCY3M      float64
 51   CNT_TRAN_AUT_TENDENCY1M      float64
 52   CNT_TRAN_AUT_TENDENCY3M      float64
 53   CNT_TRAN_CLO_TENDENCY1M      float64
 54   CNT_TRAN_CLO_TENDENCY3M      float64
 55   CNT_TRAN_MED_TENDENCY1M      float64
 56   CNT_TRAN_MED_TENDENCY3M      float64
 57   CNT_TRAN_SUP_TENDENCY1M      float64
 58   CNT_TRAN_SUP_TENDENCY3M      float64
 59   SUM_TRAN_ATM_TENDENCY1M      float64
 60   SUM_TRAN_ATM_TENDENCY3M      float64
 61   SUM_TRAN_AUT_TENDENCY1M      float64
 62   SUM_TRAN_AUT_TENDENCY3M      float64
 63   SUM_TRAN_CLO_TENDENCY1M      float64
 64   SUM_TRAN_CLO_TENDENCY3M      float64
 65   SUM_TRAN_MED_TENDENCY1M      float64
 66   SUM_TRAN_MED_TENDENCY3M      float64
 67   SUM_TRAN_SUP_TENDENCY1M      float64
 68   SUM_TRAN_SUP_TENDENCY3M      float64
 69   TRANS_AMOUNT_TENDENCY3M      float64
 70   TRANS_CNT_TENDENCY3M         float64
 71   TRANS_COUNT_ATM_PRC          float64
 72   TRANS_COUNT_NAS_PRC          float64
 73   TRANS_COUNT_SUP_PRC          float64
 74   AVG_PCT_DEBT_TO_DEAL_AMT     float64
 75   AVG_PCT_MONTH_TO_PCLOSE      float64
 76   DEAL_GRACE_DAYS_ACC_AVG      float64
 77   DEAL_GRACE_DAYS_ACC_MAX      float64
 78   DEAL_GRACE_DAYS_ACC_S1X1     float64
 79   DEAL_YQZ_IR_MAX              float64
 80   DEAL_YQZ_IR_MIN              float64
 81   DEAL_YWZ_IR_MAX              float64
 82   DEAL_YWZ_IR_MIN              float64
 83   LDEAL_ACT_DAYS_ACC_PCT_AVG   float64
 84   LDEAL_ACT_DAYS_PCT_AAVG      float64
 85   LDEAL_ACT_DAYS_PCT_CURR      float64
 86   LDEAL_ACT_DAYS_PCT_TR        float64
 87   LDEAL_ACT_DAYS_PCT_TR3       float64
 88   LDEAL_ACT_DAYS_PCT_TR4       float64
 89   LDEAL_AMT_MONTH              float64
 90   LDEAL_DELINQ_PER_MAXYQZ      float64
 91   LDEAL_DELINQ_PER_MAXYWZ      float64
 92   LDEAL_GRACE_DAYS_PCT_MED     float64
 93   LDEAL_TENOR_MAX              float64
 94   LDEAL_TENOR_MIN              float64
 95   LDEAL_USED_AMT_AVG_YQZ       float64
 96   LDEAL_USED_AMT_AVG_YWZ       float64
 97   LDEAL_YQZ_CHRG               float64
 98   LDEAL_YQZ_COM                float64
 99   LDEAL_YQZ_PC                 float64
 100  MAX_PCLOSE_DATE              float64
 101  MED_DEBT_PRC_YQZ             float64
 102  MED_DEBT_PRC_YWZ             float64
 103  CLNT_JOB_POSITION            object
 104  CLNT_JOB_POSITION_TYPE       object
 105  CLNT_SALARY_VALUE            float64
 106  CLNT_SETUP_TENOR             float64
 107  CLNT_TRUST_RELATION          object
 108  CR_PROD_CNT_CC               int64
 109  CR_PROD_CNT_CCFP             int64
 110  CR_PROD_CNT_IL               int64
 111  CR_PROD_CNT_PIL              int64
 112  CR_PROD_CNT_TOVR             int64
 113  CR_PROD_CNT_VCU              int64
 114  PACK                         object
 115  TARGET                       int64
dtypes: float64(94), int64(9), object(13)
memory usage: 317.1+ MB

In [13]:
df_all.APP_CAR  = df_all.APP_CAR .str.lower()
df_all.APP_COMP_TYPE  = df_all.APP_COMP_TYPE .str.lower()
df_all.APP_DRIVING_LICENSE  = df_all.APP_DRIVING_LICENSE .str.lower()
df_all.APP_EDUCATION  = df_all.APP_EDUCATION .str.lower()
df_all.APP_EMP_TYPE  = df_all.APP_EMP_TYPE .str.lower()
df_all.APP_KIND_OF_PROP_HABITATION  = df_all.APP_KIND_OF_PROP_HABITATION .str.lower()
df_all.APP_MARITAL_STATUS  = df_all.APP_MARITAL_STATUS .str.lower()
df_all.APP_POSITION_TYPE  = df_all.APP_POSITION_TYPE .str.lower()
df_all.APP_TRAVEL_PASS  = df_all.APP_TRAVEL_PASS .str.lower()
df_all.CLNT_JOB_POSITION  = df_all.CLNT_JOB_POSITION .str.lower()
df_all.CLNT_JOB_POSITION_TYPE  = df_all.CLNT_JOB_POSITION_TYPE .str.lower()
df_all.CLNT_TRUST_RELATION  = df_all.CLNT_TRUST_RELATION .str.lower()
df_all.PACK  = df_all.PACK .str.lower()

In [14]:
list(df_all.CLNT_TRUST_RELATION.unique())

[nan,
 'mother',
 'brother',
 'friend',
 'sister',
 'other',
 'relative',
 'daughter',
 'son',
 'father',
 'близкий ро',
 'друг',
 'отец',
 'сестра',
 'сын',
 'мать',
 'муж',
 'брат',
 'дальний ро',
 'дочь',
 'жена']

In [15]:
df_all.CLNT_TRUST_RELATION.replace('mother','мать',inplace=True)
df_all.CLNT_TRUST_RELATION.replace('brother','брат',inplace=True)
df_all.CLNT_TRUST_RELATION.replace('friend','друг',inplace=True)
df_all.CLNT_TRUST_RELATION.replace('sister','сестра',inplace=True)
df_all.CLNT_TRUST_RELATION.replace('other','другое',inplace=True)
df_all.CLNT_TRUST_RELATION.replace('relative','родственник',inplace=True)
df_all.CLNT_TRUST_RELATION.replace('daughter','дочь',inplace=True)
df_all.CLNT_TRUST_RELATION.replace('son','сын',inplace=True)
df_all.CLNT_TRUST_RELATION.replace('father','отец',inplace=True)

In [16]:
list(df_all.CLNT_TRUST_RELATION.unique())

[nan,
 'мать',
 'брат',
 'друг',
 'сестра',
 'другое',
 'родственник',
 'дочь',
 'сын',
 'отец',
 'близкий ро',
 'муж',
 'дальний ро',
 'жена']

In [17]:
df_all.APP_CAR.where(df_all.APP_CAR.str.replace(' ','').str.isalpha(), np.nan, inplace=True)
df_all.APP_COMP_TYPE.where(df_all.APP_COMP_TYPE.str.replace(' ','').str.isalpha(), np.nan, inplace=True)
df_all.APP_DRIVING_LICENSE.where(df_all.APP_DRIVING_LICENSE.str.replace(' ','').str.isalpha(), np.nan, inplace=True)
df_all.APP_EDUCATION.where(df_all.APP_EDUCATION.str.replace(' ','').str.isalpha(), np.nan, inplace=True)
df_all.APP_EMP_TYPE.where(df_all.APP_EMP_TYPE.str.replace(' ','').str.isalpha(), np.nan, inplace=True)
df_all.APP_KIND_OF_PROP_HABITATION.where(df_all.APP_KIND_OF_PROP_HABITATION.str.replace(' ','').str.isalpha(), np.nan, inplace=True)
df_all.APP_MARITAL_STATUS.where(df_all.APP_MARITAL_STATUS.str.replace(' ','').str.isalpha(), np.nan, inplace=True)
df_all.APP_POSITION_TYPE.where(df_all.APP_POSITION_TYPE.str.replace(' ','').str.isalpha(), np.nan, inplace=True)
df_all.APP_TRAVEL_PASS.where(df_all.APP_TRAVEL_PASS.str.replace(' ','').str.isalpha(), np.nan, inplace=True)
df_all.CLNT_JOB_POSITION.where(df_all.CLNT_JOB_POSITION.str.replace(' ','').str.isalpha(), np.nan, inplace=True)
df_all.CLNT_JOB_POSITION_TYPE.where(df_all.CLNT_JOB_POSITION_TYPE.str.replace(' ','').str.isalpha(), np.nan, inplace=True)
df_all.CLNT_TRUST_RELATION.where(df_all.CLNT_TRUST_RELATION.str.replace(' ','').str.isalpha(), np.nan, inplace=True)

In [18]:
list(df_all.APP_CAR.unique())

[nan, 'n', 'y']

In [19]:
list(df_all.APP_COMP_TYPE.unique())

[nan, 'private', 'state', 'ip', 'inter']

In [20]:
list(df_all.APP_DRIVING_LICENSE.unique())

[nan, 'y', 'n']

In [21]:
list(df_all.APP_EDUCATION.unique())

[nan, 's', 'hh', 'h', 'ss', 'uh', 'a', 'i', 'us', 'e', 'hi', 'av', 'ac']

In [22]:
list(df_all.APP_EMP_TYPE.unique())

[nan, 'private', 'state', 'ip', 'inter']

In [23]:
list(df_all.APP_KIND_OF_PROP_HABITATION.unique())

[nan, 'so', 'rent', 'other', 'jo', 'nprivat']

In [24]:
list(df_all.APP_MARITAL_STATUS.unique())

[nan, 'd', 'm', 'v', 't', 'n', 'w', 'c']

In [25]:
list(df_all.APP_POSITION_TYPE.unique())

[nan, 'specialist', 'manager']

In [26]:
list(df_all.APP_TRAVEL_PASS.unique())

[nan, 'n', 'y']

In [27]:
list(df_all.CLNT_JOB_POSITION.unique())

['начальник отдела',
 nan,
 'генеральный директор',
 'менеджер иао',
 'директор',
 'предприниматель',
 'архитектор',
 'экономист',
 'менеджер',
 'системотехник',
 'медицинский представитель',
 'дистрибьютор',
 'техник геофизик',
 'специалист',
 'специалист по страхованию',
 'главныцй бухгалтер',
 'заместитель генерального директора',
 'продавец',
 'программист',
 'специалист отдела кадров',
 'специалист отдела продаж',
 'заместитель начальника отдела',
 'звукоинженер',
 'матрос',
 'альпинист',
 'курьер',
 'руководитель направления',
 'художник',
 'индивидуальный предприниматель',
 'лаборант',
 'исполнительный директор',
 'финансовый директор',
 'врач',
 'водитель',
 'маркетолог',
 'врач анестезиолог реаниматолог',
 'артдиректор',
 'разработчик аппаратных средств',
 'бухгалтер',
 'администратор',
 'старший тех специалист',
 'мастер механик',
 'дизайнер',
 'ведущий специалист',
 'начальник участка',
 'инженер',
 'руководитель отдела',
 'прессаташе',
 'управляющий магазином',
 'управляющая',
 'старший механик',
 'заместитель ген директора',
 'кладовщик',
 'начальник дч',
 'автослесарь',
 'ип',
 'главный специалист по обработке',
 'учитель',
 'соцработник',
 'зам директора',
 'технический директор',
 'менеджер по закупкам',
 'оператор',
 'слесарь мср',
 'начальник отдела продаж',
 'региональный представитель',
 'мастер',
 'мастер парикмахер',
 'прораб',
 'медицинский менеджер',
 'руководитель',
 'мастер во и бло',
 'зам директора по развитию',
 'торговый представитель',
 'контроллер',
 'начальник цеха',
 'специалист цпк',
 'директор фирмы',
 'стоматолог',
 'экспедитор',
 'старший преподаватель',
 'директор сбм',
 'коммерческий директор',
 'второй помошник капитана',
 'служащий',
 'страховой консультант',
 'палатная санитарка',
 'главный эксперт',
 'редактор',
 'кровельщик',
 'зам директор по развитию',
 'руководитель проекта',
 'консультант',
 'менеджер орп',
 'преподаватель',
 'специалист по маркетингу',
 'ведущий инженер',
 'секретарь',
 'разработчик',
 'установщик мебели',
 'старший экономист',
 'снабженец',
 'охранник',
 'заместитель руководителя',
 'заместитель начальника сб',
 'страховой агент',
 'менеджер по продажам',
 'главный специалист',
 'координатор проектов',
 'системный администратор',
 'старший повар',
 'директор по развитию',
 'руководитель службы персонала',
 'главный механик',
 'менеджер по it проектам',
 'аспирант',
 'ветадвайзер',
 'механик',
 'шлифовщик',
 'доцент кафедры менеджмента',
 'програмист',
 'судья',
 'фармацевт',
 'частный инвестор',
 'эксперт по гарантии',
 'директор филиала приволжский',
 'начальник базы',
 'менеджер по персоналу',
 'заведующая отделением',
 'директор филиала',
 'рукокодитель направления',
 'следователдь по увд',
 'соц работник',
 'управляющий',
 'руководитель отдела продаж',
 'плиточник',
 'референт',
 'медсестра',
 'хостес',
 'главный бухгалтер',
 'мерчендайзер',
 'психотерапевт',
 'инженер проекта',
 'стилист',
 'руководитель отдела сопровождения',
 'редактор отдела культуры и спорта',
 'слесарь',
 'старший администратор',
 'специалист ооо',
 'биржевой брокер',
 'начальник отдела вк',
 'помощник гипа',
 'повар салатного цеха',
 'руководитель проектов',
 'начальник службы',
 'освобожденный бригадир',
 'видео дизайнер',
 'руководитель организации',
 'глава администрации',
 'автомеханник',
 'инженер механик',
 'ассистент',
 'юрист',
 'охранник гбр',
 'старший научный сотрудник',
 'начальник контрольного управления',
 'помощник руководителя',
 'агент по продажам',
 'операционист транспортного отдела',
 'упаковщик',
 'проэктный менеджер',
 'оператор чпу',
 'webmaster',
 'техник программист',
 'психолог',
 'член бригады подготовки и открытия',
 'контролёр кпво',
 'независимый предприниматель амway',
 'техник',
 'командир воздушного судна',
 'доцент',
 'заведующий клавишной мастерской',
 'руководитель группы дмс',
 'супервайзер',
 'системный специалист',
 'повар',
 'советник',
 'педагог дополнительного образования',
 'инженер по наладке и установке',
 'старший инспекор',
 'специалист по обучению персонала',
 'финансовый контролер',
 'агент по недвижимости',
 'директор департамента',
 'главный врач',
 'ведущий эксперт',
 'заместитель директора',
 'эксперт',
 'адвокат',
 'журналист',
 'докер',
 'завскладом готовой продукции',
 'страший продавец консультант',
 'профессор',
 'старший специалист одо',
 'начальник орского отделения',
 'главный инженер',
 'юрисконсульт',
 'техник пто',
 'директор проектов',
 'дежурный по станции',
 'ген директор',
 'специалист по рекламации',
 'инженер программист',
 'главный специалист отдела выставок',
 'представитель компании',
 'тренер',
 'региональный менеджер',
 'сити менеджер',
 'начальник отдела вэд',
 'настоятель',
 'ведущий аналитик',
 'студент',
 'парикмахер',
 'артист',
 'руководитель отдела рекламы',
 'мастер производственного участка',
 'старший инспектор',
 'старший специалист',
 'главный архитектор',
 'начальник управления',
 'магистр',
 'главный специалист пто',
 'менеджер по коммуникациям',
 'комерческий директор',
 'заместитель коммерческого директора',
 'продюсер',
 'заместитель главного бухгалтера',
 'помошни к машениста',
 'замю директора',
 'официант',
 'третий инженер',
 'студентка',
 'врачь',
 'литейщик',
 'художник постановщик',
 'стюардесса',
 'электрообмотчик',
 'главный геолог',
 'менеджер проектов',
 'менеджер по работе с клиентами',
 'главный технолог',
 'второй помощник',
 'специалист по то',
 'заведующий сектором',
 'глава кфх',
 'начальник отдела логистики',
 'инструктор пдп',
 'строитель',
 'старший региональный менеджер',
 'дворник',
 'капитан',
 'федеральный менеджер проектов',
 'старший руководитель направлений',
 'член комиссии',
 'помощник судьи',
 'старший юрист',
 'фрилансер',
 'машинист крана',
 'менеджер направления вич спид',
 'провизор  технолог',
 'начальник департамента лизинговых',
 'сотрудник',
 'тренер преподователь',
 'помощник бухгалтера',
 'менеджер склада',
 'радиомеханик по обслуживанию рта',
 'сменный мастер группы',
 'разнорабочий',
 'менеджер по прямому маркетингу',
 'внс',
 'руководитель по работе с клиентами',
 'специалист тендерного отдела',
 'сторож',
 'третий секретарь',
 'технический консультант',
 'сборщик достройщик',
 'ведущий спесиалист',
 'начальник управления делами',
 'пенсионер',
 'аналитик',
 'менеджер по развитию бизнеса',
 'начальник',
 'грузчик',
 'старшая медсестра',
 'заместитель  директора',
 'председатель',
 'управляющий филиала',
 'учредитель альянс инвест',
 'технолог',
 'зам нач юр отдела',
 'бизнес аналитик',
 'директор по работе с инвесторами',
 'бурильщик',
 'помощник президента',
 'старший инженер программист',
 'контент менеджер',
 'помощник начальника',
 'электромонтер',
 'нпа',
 'руковдитель представительства',
 'президент',
 'фитер',
 'начальник пожароной',
 'кладавщик',
 'старший юристконсульт',
 'подземный горнорабочий',
 'бармен',
 'начальник транспортного отдела',
 'старший аппаратчик',
 'дерматолог',
 'зам начальника асу',
 'директор по региональным продажам',
 'подсобный рабочий',
 'советник президента',
 'менеджер отдела продаж',
 'помощник  капитана',
 'риэлтер',
 'начальник отдела внедрения',
 'начальник производства',
 'главный специалист опу',
 'инспектор',
 'переводчик',
 'зам начальника ксб',
 'координатор продаж',
 'ведущий программист',
 'генеральный деректор',
 'гениральный директор',
 'машинист насосных установок',
 'ведущий програмист',
 'инженер птo',
 'консультатнт',
 'младший научный сотрудник',
 'начальник юридического отдела',
 'телеведущий',
 'логист',
 'не работает',
 'мед сестра',
 'заведующий хранилищем',
 'гл бухгалтер',
 'регистратор',
 'автомеханик',
 'начальник  отдела',
 'менеджер по продукту',
 'координатор',
 'начальник отдела снабжения',
 'независимый предприниматель',
 'костюмер',
 'зам глав бухгалтер',
 'мастер производства',
 'начальник смены',
 'монтажник',
 'милиционер',
 'маляр',
 'главный диспетчер',
 'концертный директор',
 'аппаратчик химвода',
 'директор оптовой компании',
 'ведущий разработчик',
 'рабочий',
 'бригадир',
 'электрослесарь подземный',
 'преподаватель немецкого языка',
 'сварщик монтажник',
 'руководитель группы',
 'директор по качеству',
 'фотограф',
 'пиар менеджер',
 'риелтор',
 'помошник бухгалтера',
 'портье',
 'плитальщик',
 'грузовой агент',
 'консультанат',
 'финансовый консультант',
 'старший оператор',
 'замерщик',
 'заместитель директора по проектиров',
 'инженер  категории',
 'следователь',
 'преподаватель английского языка',
 'директор по продажам',
 'гид',
 'помощник генерального директора',
 'машинист технологических компрессор',
 'председатель совета директоров',
 'менджер',
 'старший следователь',
 'линейщик',
 'менеджер вэд',
 'инженер проэктировщик',
 'менеджер орэсп',
 'зам директор',
 'инструктор',
 'младший воспитатель',
 'исполнительный секретарь',
 'медицинский предстовитель',
 'ассистент кафедры',
 'офис менеджер',
 'командир авиационной эскадрильи',
 'региональный управляющий',
 'технический менеджер',
 'исполняющая обязанности директора',
 'агент',
 'мерчандайзер',
 'электромеханик',
 'представитель по развитию',
 'оператор азс',
 'коммерческий агент',
 'горный нормировщик',
 'инженер по гарантии',
 'менеждер',
 'фельдшер',
 'менеджер клиентского отдела',
 'специалист по продажам',
 'телеоператор',
 'хореограф',
 'управляющий директор',
 'специалист по календарному планиров',
 'бригадир смены',
 'мастер чистоты',
 'геймдизайнер',
 'веб дизайнер',
 'помощник машиниста',
 'комплектовщик',
 'ассистент переводчика',
 'заместитель директора департамента',
 'артист хора',
 'киномеханик',
 'старший мастер',
 'швея',
 'руководитель оп новосибирск',
 'инженер конструктор',
 'заведущий отделением',
 'водитель экспедитор',
 'руководитель рубрики',
 'специалист по тестированию',
 'генеральный менеджер',
 'пластический хирург',
 'сборщик мебели',
 'начальник дирекции',
 'риэлтор',
 'пердприниматель',
 'специалист по контекстной рекламе',
 'закупщик',
 'борт проводник',
 'монтер пути',
 'директор по проектам',
 'спортсмен профессионал',
 'инженер разработчик асу',
 'корреспондент',
 'бугалтер',
 'доцент кафедры',
 'специалист мто',
 'старший консультант',
 'водитель автомобиля',
 'промоутер',
 'начальник мастерской авто тэч',
 'диспетчер',
 'мастер по пошиву одежды',
 'модель',
 'комерческии директор',
 'заместитель главного врача по кэр',
 'старший группы гбр',
 'инспектор по бронированию',
 'администратор проекта',
 'научный сотрудник',
 'учащийся',
 'методист',
 'руководитель отдела снабжения',
 'юристконсульт',
 'дежурная медсестра',
 'ведущий научный сотрудник',
 'персональный менеджер',
 'директор по производству',
 'инженер связи',
 'начальник логистики',
 'инженер технолог',
 'консультант по страхованию',
 'руководитель финансового отдела',
 'зам главного редактора рбк тв',
 'ландшафтный дизайнер',
 'музыкальный руководитель',
 'дмректор',
 'менеджер пиар',
 'помощник преподавателя',
 'земеститель технического директора',
 'замдиректора',
 'скорняг',
 'старший техник',
 'лаборант хим анализа',
 'модельщик',
 'главный экономист',
 'пенионер',
 'интернет маркетолог',
 'кае',
 'управляющий администратор',
 'ногтевой мастер',
 'менеджер по поставкам',
 'продьюссер',
 'специалист опп',
 'начальник отдела рекламы',
 'второй штурман',
 'оперуполномоченный',
 'охраник',
 'специалист по регистрации лс',
 'директор магазина',
 'педагог',
 'бульдозерист',
 'сварщик',
 'старший менеджер по продажам',
 'руководитель сервис службы',
 'manager',
 'домохозяйка',
 'уборщик',
 'инженер пто',
 'директора',
 'начальник строительного участка',
 'врач хирург',
 'recruitment meneger',
 'начальник сб',
 'электромонтер по рем',
 'товаровед',
 'мастер строительного участка',
 'мастер цеха',
 'фототехник',
 'документовед',
 'заведующий производства',
 'менеджер по категории',
 'педиатр',
 'помощник бурильщика',
 'оператор днг',
 'началльник отдела маркетинга',
 'безработный',
 'кассир',
 'старший кассир',
 'инженер по охране труда',
 'библиотекарь оир нб',
 'sales meneger',
 'техник опс',
 'электромеханник',
 'заместитель главного инженера',
 'ведущий конструктор',
 'начальник отдела реализации',
 'ведущий экономист',
 'тестировщик',
 'механизатор',
 'оптимизатор',
 'начальник отдела ит',
 'фрезеровщик',
 'военнослужащий',
 'почтальон',
 'проводник',
 'старший пожарный',
 'уборщица',
 'директор по ит',
 'начальник группы',
 'ит директор',
 'мастер промзоны',
 'административный директор',
 'руководитель отдела разработки',
 'ипбоюл',
 'менеджер по туризму',
 'начальник гпрб',
 'руководитель бюро продаж',
 'диджей',
 'старший менеджер',
 'информационная справочная',
 'старший инженер',
 'старший диспетчер',
 'специалист по развитию партнерских',
 'начальник территориального отдела',
 'территориальный менеджер',
 'начальник отдела контроля',
 'менеджер по качеству',
 'зам ген директора',
 'заместитель начальника экспедиции',
 'учредитель',
 'трубопроводчик',
 'директор по маркетингу',
 'менеджер по рекламе',
 'менеджер логистики',
 'руководитель рецепции',
 'продюссер',
 'креативный директор',
 'военный пенсионер',
 'старший товаровед',
 'главный энергетик',
 'представитель по урфо',
 'менеджер по перевозкам',
 'садчик',
 'начальник конструкторскогобюро',
 'специалист брокерского отдела',
 'специалист ора',
 'индивидуальный предпринимаьель',
 'монтажник опс',
 'генеральный  директор',
 'инженер по ремонту',
 'координатор окзиц',
 'ассистент менеджера по персоналу',
 'кочегар',
 'оператор станков с чпу',
 'менеджер по безопасности',
 'электрослесарь',
 'директор по экономике',
 'старший оперуполномоченный',
 'специалист по недвижимости',
 'заведующий лабараторией',
 'начальник отдела кадров',
 'резчик',
 'вокалист',
 'помошник руководителя',
 'руководитель регионального отдела',
 'редактор моды',
 'партнер',
 'руководитель отдела сбыта',
 'начальник ок',
 'администартор',
 'ведуший маркетолог',
 'менеджер по сбыту',
 'начальник отдела сбыта',
 'контролер',
 'хирург',
 'помощник менеджера по продажам',
 'специалист по выдаче',
 'водитель международник',
 'электромонтажник',
 'газоэлекторосварщик',
 'старший аналитик',
 'бетонщик',
 'зам начальника отдела маркетинга',
 'режиссер новостей',
 'старший объекта',
 'помощник директора',
 'руководитель абоненского отдела',
 'соучредитель',
 'массажист',
 'начальник отдела охраны труда',
 'кастомер',
 'зам начальника отдела',
 'командир',
 'специалист склада',
 'слесарь по ремонту',
 'инженер отд мтc',
 'специалист по рекламе',
 'заместитель финансового директора',
 'дальнобойщик',
 'машинист холодильных установок',
 'инспектор по кадрам',
 'юрист консул',
 'артист оркестра',
 'управляющий партнер',
 'руководитель направления онлайн дис',
 'врач психотерапевт',
 'мененджер',
 'системный архитектор',
 'газоэлектросварщик',
 'проректор по воспитательной работе',
 'сборщик',
 'руководитель отдела развития',
 'свадебный фотограф',
 'пожарный',
 'помощник менеджера',
 'продавец консультант',
 'менеджер оркк',
 'специалист по рекламациям',
 'менеджер healthclub',
 'редактор отдела',
 'помощник капитана',
 'менеджер по мультимодельным перевоз',
 'начальник департамента',
 'председатель правления',
 'директор по экономике и финансам',
 'видеоинженер',
 'территориальный управлящий',
 'начальник рекламного отдела',
 'машининст',
 'завхоз',
 'sekond engineer',
 'декретный отпуск',
 'трейдер',
 'электромантер',
 'начальник участка металообработки',
 'подручный сталевара',
 'инструктор по вождению',
 'охраннмик',
 'геолог',
 'инженер по текущей эксплуатации',
 'эмбриолог',
 'начальник сдо',
 'конструктор',
 'старший инженер по качеству',
 'лобарант',
 'начальник группы обучения',
 'менеджер по производству',
 'учередитель',
 'приемщица',
 'геннеральный директор',
 'региональный директор по продажам',
 'консультант по табачной продукции',
 'стамотолог',
 'менеджер отдела закупок',
 'редактор викторин',
 'сценарист',
 'начальник отдела маркетинга',
 'официантка',
 'заместитель главы',
 'футболист',
 'разработчик програмного обеспечения',
 'судоводитель',
 'начальник отдела снабжения и сбыта',
 'сервисный инженер',
 'специалист по приемке',
 'художник по костюмам',
 'начальниу участка',
 'руководитель центра',
 'глав врач',
 'ведущий менеджер',
 'вед специалист',
 'специалист по разработке систем иб',
 'начальник юридического департамента',
 'юрист консультант',
 'бизнес тренер',
 'системный аналитик',
 'менеджер по учету',
 'главный специалист отдела снабжения',
 'ассистент менеджера',
 'младший разработчик',
 'пресвитер',
 'дистребьютор',
 'старший программист',
 'советник генерального директора',
 'инспектор отдела кадров',
 'ведущий специалист ит',
 'торговый агент',
 'менеджер по рекламации',
 'зам начальника отдела рекламы',
 'асситент',
 'риск менеджер',
 'безработная',
 'социальный работник',
 'менеджер экспедиторского отдела',
 'преподаватель изо',
 'сотрудник сэб',
 'специалист отдела клиентского серви',
 'президент фонда',
 'менеджер торгового зала',
 'временно не работает',
 'установщик дверей',
 'боцман',
 'менежер по продажам',
 'профессор кафедры',
 'региональный директор по маркетингу',
 'стажор',
 'аварийный комиссар',
 'qc certification specialist',
 'аппаратчик',
 'смм специалист',
 'специалист по перевозкам',
 'регулировщик радиоаппаратуры',
 'менеджер по работе с проектами',
 'помошник директора',
 'преподователь',
 'старший продавец консультант',
 'specialist',
 'нач отдела',
 'пенсинер',
 'директор тренинговых программ',
 'руководитель группы вэд',
 'ассистент кафедры иб',
 'актриса',
 'преподаватель воскресной школы',
 'ассистент врача',
 'владелец',
 'менеджер по управлению контентом',
 'директор универсама',
 'директор по персооналу',
 'ауп',
 'договорник',
 'флорист',
 'концертмейстер',
 'преподаватель аспирант',
 'руководитель коммерческого отдела',
 'рабочий по обслуживанию',
 'salesperson',
 'штамповщик',
 'оператор сто',
 'заведущий кафедрой',
 'клинический ординатор',
 'менеджер по логистике',
 'электрогазосварщик',
 'сотрудник отдела сопровождения',
 'специалист по ит',
 'менеджер по маркетингу',
 'энергетик',
 'оператор при дежурного по станции',
 'специалист по эк оценке проектов',
 'докер механизатор',
 'другое',
 'оператор эвм',
 'электромантажник',
 'тме',
 'консультант одела',
 'руководитель отдела учета товаров',
 'старший мастер добычи',
 'главный тренер',
 'контроллер окк',
 'визажист',
 'специалист отдела денежного обращен',
 'глава представительства',
 'врач стоматолог',
 'контролер отк',
 'частный предприниматель',
 'региональный руководитель',
 'начальник комерческого отдела',
 'заместитель директора по пср',
 'начальник кафедры',
 'менеджер по маркентингу',
 'начальник сектора',
 'руководитель филиала',
 'оператор связи',
 'инженер по то',
 'специалист по логистике',
 'тороговый представитель',
 'специалист оско',
 'начальник стс',
 'врач про лфр',
 'вед научн сотрудник',
 'начальник отдела приема',
 'начальник службы художников',
 'начальник службы асту',
 'рубщик',
 'старший помощник капитана',
 'ведущий юрисконсульт',
 'начальник ит',
 'начальник ахо',
 'не работаю',
 'ведущий ветеринарный врач',
 'слесарь кип',
 'управляющий офисом продаж',
 'старший разработчик по',
 'координатор международных проектов',
 'инженер по кинопоказу',
 'главный советник',
 'ординатор',
 'менеждер по закупкам',
 'менеджер товарной категории',
 'координатор отдела продаж',
 'оператор скуд',
 'медиадиректор',
 'упровляющий проектами',
 'пиар директор',
 'начальник кб',
 'ведущий менеджер по маркетингу',
 'начальник офиса',
 'машинист автокрана',
 'лингвист',
 'штурман',
 'инженер оопп',
 'советник директора',
 'инженер технической поддержки',
 'зам главного бухгалтера',
 'формовщик',
 'метрдотель',
 'стажер адвокат',
 'стрелок',
 'таможенный инспектор',
 'составитель поездов',
 'мастер слесарного участка',
 'it',
 'помощник адвоката',
 'главный редактор',
 'секретарь руководства',
 'менеджер по развитию территории',
 'менеджер по товародвижению',
 'корпоративный тренер',
 'директор по закупкам',
 'начальник отдела транспорта',
 'менеджер по логистическим перевозка',
 'менеджер по контекстной рекламе',
 'сотрудник  тендоргоного отдела',
 'копирайтер',

In [28]:
list(df_all.CLNT_JOB_POSITION_TYPE.unique())

[nan, 'specialist', 'manager']

In [29]:
list(df_all.PACK.unique())

['k01',
 '102',
 '105',
 'o01',
 '103',
 '101',
 '107',
 '301',
 '104',
 '108',
 '109',
 'm01']

In [30]:
list(df_all.CLNT_TRUST_RELATION.unique())

[nan,
 'мать',
 'брат',
 'друг',
 'сестра',
 'другое',
 'родственник',
 'дочь',
 'сын',
 'отец',
 'близкий ро',
 'муж',
 'дальний ро',
 'жена']

In [31]:
df_all['APP_COMP_TYPE'].compare(df_all['APP_EMP_TYPE'])

Empty DataFrame
Columns: [self, other]
Index: []

In [32]:
df_all = df_all.drop(columns='APP_EMP_TYPE')

In [33]:
df_all.shape

(355190, 115)

In [34]:
df_all['APP_CAR'].compare(df_all['APP_TRAVEL_PASS'])

       self other
171131    y     n
117633    y     n
52766     y     n
164421    y     n
217603    y     n
...     ...   ...
264911    n     y
141333    y     n
294939    y     n
298480    y     n
95698     y     n

[25011 rows x 2 columns]

In [37]:
df_all['APP_CAR'].compare(df_all['APP_DRIVING_LICENSE'])

       self other
114851    n     y
144330    n     y
313708    n     y
95165     n     y
171131    y     n
...     ...   ...
146717    n     y
214406    n     y
141333    y     n
294939    y     n
95698     y     n

[19255 rows x 2 columns]

In [35]:
df_all['APP_POSITION_TYPE'].compare(df_all['CLNT_JOB_POSITION_TYPE'])

              self       other
153682     manager         NaN
278331  specialist         NaN
117633     manager  specialist
52766   specialist         NaN
82505          NaN  specialist
...            ...         ...
37093   specialist         NaN
343770  specialist         NaN
214406     manager         NaN
234846  specialist         NaN
298480         NaN     manager

[22498 rows x 2 columns]

In [36]:
print(df_all)

            ID  CNT_ACCEPTS_MTP  CNT_ACCEPTS_TK  PRC_ACCEPTS_A_AMOBILE  \
179094  146841              NaN             NaN                    NaN
5351    146842              NaN             NaN                    NaN
206996  146843              0.0             0.0                    0.0
145569  146844              NaN             NaN                    NaN
329776  146845              NaN             NaN                    NaN
...        ...              ...             ...                    ...
352062  590822              0.0             0.0                    0.0
255813  590823              0.0             0.0                    0.0
233095  590825              NaN             NaN                    NaN
353508  590826              NaN             NaN                    NaN
330689  590828              NaN             NaN                    NaN

        PRC_ACCEPTS_A_ATM  PRC_ACCEPTS_A_EMAIL_LINK  PRC_ACCEPTS_A_MTP  \
179094                NaN                       NaN                NaN
5351                  NaN                       NaN                NaN
206996                0.0                       0.0                0.0
145569                NaN                       NaN                NaN
329776                NaN                       NaN                NaN
...                   ...                       ...                ...
352062                0.0                       0.0                0.0
255813                0.0                       0.0                0.0
233095                NaN                       NaN                NaN
353508                NaN                       NaN                NaN
330689                NaN                       NaN                NaN

        PRC_ACCEPTS_A_POS  PRC_ACCEPTS_A_TK  PRC_ACCEPTS_MTP  ...  \
179094                NaN               NaN              NaN  ...
5351                  NaN               NaN              NaN  ...
206996                0.0               0.0              0.0  ...
145569                NaN               NaN              NaN  ...
329776                NaN               NaN              NaN  ...
...                   ...               ...              ...  ...
352062                0.0               0.0              0.0  ...
255813                0.0               0.0              0.0  ...
233095                NaN               NaN              NaN  ...
353508                NaN               NaN              NaN  ...
330689                NaN               NaN              NaN  ...

        CLNT_SETUP_TENOR  CLNT_TRUST_RELATION  CR_PROD_CNT_CC  \
179094          1.593023                  NaN               0
5351            1.587647                  NaN               0
206996          1.587647                  NaN               0
145569          1.583333                  NaN               0
329776          1.583333                  NaN               0
...                  ...                  ...             ...
352062          8.963872                  NaN               0
255813          8.963872                  NaN               0
233095          8.966560                  NaN               0
353508          8.966560                  NaN               0
330689          8.961184               сестра               0

        CR_PROD_CNT_CCFP  CR_PROD_CNT_IL  CR_PROD_CNT_PIL  CR_PROD_CNT_TOVR  \
179094                 0               0                0                 0
5351                   0               0                0                 0
206996                 0               0                0                 0
145569                 0               0                0                 0
329776                 0               0                0                 0
...                  ...             ...              ...               ...
352062                 0               0                0                 2
255813                 0               0                0                 0
233095                 0               0                0                 0
353508                 0               0                0                 1
330689                 0               0                0                 1

        CR_PROD_CNT_VCU  PACK  TARGET
179094                0   k01       0
5351                  0   102       0
206996                0   102       0
145569                0   k01       0
329776                0   102       0
...                 ...   ...     ...
352062                0   104       0
255813                0   104       0
233095                0   k01       0
353508                0   o01       0
330689                0   k01       1

[355190 rows x 115 columns]